env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: 0
  react/jsx-uses-vars:
    - 2
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
