env:
  browser: true
  es6: true
  amd: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
plugins:
  - react
parser: '@babel/eslint-parser'
parserOptions:
  sourceType: module
  requireConfigFile: false
settings:
  react:
    version: detect
rules:
  react/jsx-uses-vars: 2
  react/react-in-jsx-scope: 0
